import Head from 'next/head'
import Image from 'next/image'
import Container from './components/Container'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Central North Region Karen Baptist Churches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container/>
    </div>
  )
}
