import Head from 'next/head'
import Image from 'next/image'
import Container from './components/Container'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Central North Region Karen Baptist Churches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet"/>
      </Head>
      <Container/>
    </div>
  )
}
